# config/packages/knpu_oauth2_client.yaml
knpu_oauth2_client:
    clients:
        # the key "google" can be anything, it
        # will create a service: "knpu.oauth2.client.google"
        google:
            # this will be one of the supported types
            type: google
            client_id: '%env(OAUTH_GOOGLE_ID)%' #il le recupere dans .env.local qui est en .gitignore
            client_secret: '%env(OAUTH_GOOGLE_SECRET)%' #il le recupere dans .env.local qui est en .gitignore
            # the route that you're redirected to after
            redirect_route: connect_google_check
            redirect_params: {}